apiVersion: v2
name: ack-chart
description: A Helm chart containing all ACK charts as sub-charts
type: application
version: 46.13.3
appVersion: "0.0.0"
dependencies:
  - name: apigatewayv2-chart
    alias: apigatewayv2
    version: 1.0.16
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: apigatewayv2.enabled
  - name: applicationautoscaling-chart
    alias: applicationautoscaling
    version: 1.0.17
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: applicationautoscaling.enabled
  - name: cloudfront-chart
    alias: cloudfront
    version: 1.0.0
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: cloudfront.enabled
  - name: cloudtrail-chart
    alias: cloudtrail
    version: 1.0.14
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: cloudtrail.enabled
  - name: documentdb-chart
    alias: documentdb
    version: 1.0.0
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: documentdb.enabled
  - name: dynamodb-chart
    alias: dynamodb
    version: 1.2.14
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: dynamodb.enabled
  - name: ec2-chart
    alias: ec2
    version: 1.2.20
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: ec2.enabled
  - name: ecr-chart
    alias: ecr
    version: 1.0.18
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: ecr.enabled
  - name: ecs-chart
    alias: ecs
    version: 1.0.0
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: ecs.enabled
  - name: efs-chart
    alias: efs
    version: 1.0.0
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: efs.enabled
  - name: eks-chart
    alias: eks
    version: 1.4.5
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: eks.enabled
  - name: elbv2-chart
    alias: elbv2
    version: 1.0.0
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: elbv2.enabled
  - name: emrcontainers-chart
    alias: emrcontainers
    version: 1.0.12
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: emrcontainers.enabled
  - name: eventbridge-chart
    alias: eventbridge
    version: 1.0.14
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: eventbridge.enabled
  - name: iam-chart
    alias: iam
    version: 1.3.12
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: iam.enabled
  - name: keyspaces-chart
    alias: keyspaces
    version: 1.0.0
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: keyspaces.enabled
  - name: kms-chart
    alias: kms
    version: 1.0.16
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: kms.enabled
  - name: lambda-chart
    alias: lambda
    version: 1.5.1
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: lambda.enabled
  - name: memorydb-chart
    alias: memorydb
    version: 1.0.5
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: memorydb.enabled
  - name: opensearchservice-chart
    alias: opensearchservice
    version: 1.0.0
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: opensearchservice.enabled
  - name: pipes-chart
    alias: pipes
    version: 1.0.11
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: pipes.enabled
  - name: prometheusservice-chart
    alias: prometheusservice
    version: 1.2.13
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: prometheusservice.enabled
  - name: rds-chart
    alias: rds
    version: 1.4.4
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: rds.enabled
  - name: s3-chart
    alias: s3
    version: 1.0.16
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: s3.enabled
  - name: sagemaker-chart
    alias: sagemaker
    version: 1.2.12
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: sagemaker.enabled
  - name: sfn-chart
    alias: sfn
    version: 1.0.14
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: sfn.enabled
  - name: sns-chart
    alias: sns
    version: 1.0.13
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: sns.enabled
  - name: sqs-chart
    alias: sqs
    version: 1.0.16
    repository: oci://public.ecr.aws/aws-controllers-k8s
    condition: sqs.enabled
